### ISSUE TITLE
Redesign qt wallet with new graphics and new ticker to XED

### ISSUE THREAD

**Issue by Demoncoin** [Demoncoin/demoncoin#2]
Redesign qt wallet:

<img width="400" alt="screen shot 2016-09-06 at 21 05 17" src="https://cloud.githubusercontent.com/assets/20825196/18289188/49273230-7476-11e6-98a6-437dc7c30def.png">

Change ticker to XED and compile Win and Mac qt wallets

logo: http://i.imgur.com/uyQQpMr.png
text: http://i.imgur.com/Zg9esLk.png
Splash: http://i.imgur.com/BZn1PFM.jpg

**Comment by kdsmith18542** [comment]
do you want to keep the splash page the same

**Comment by Demoncoin** [comment]
No, sorry, i'll upload a splash screen, just a sec.

**Comment by kdsmith18542** [comment]
ok and do you want it to look exactly like the above picture?

**Comment by kdsmith18542** [comment]
i have a rough draft if you want anything else added let me know

**Comment by Demoncoin** [comment]
That's perfect, let me check and then you can take the BTC bounty and I'll throw in some XED

**Comment by Demoncoin** [comment]
I've merged your ticker changes

**Comment by kdsmith18542** [comment]
ok ill upload give me 2 shakes

**Comment by kdsmith18542** [comment]
ill submit another pull request after i upload for the changes to be added to the github source aswell 
the mac wallet will take me a few hours as i dont have a mac and will have to setup a linux build enviroment to crosscompile it

**Comment by kdsmith18542** [comment]
heres the windows wallet link

https://drive.google.com/open?id=0B23IEg9m9DRtbDB5ckxiYWZzeVU

**Comment by Demoncoin** [comment]
This has been completed for now.
